# Generated by Django 2.2 on 2019-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=200)),
                ('assay_type', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('body_site', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=200)),
                ('log', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sample_type', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('urbanization', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('target_amplicon', models.CharField(max_length=200)),
            ],
        ),
    ]
